[local]
localhost ansible_connection=local

[docker]
# Assumindo que o container se chama 'alvo-debian' e temos acesso direto
# Em um cenário real de curso, usaríamos IP ou 'ansible_connection=docker'
alvo-debian ansible_connection=docker ansible_user=root

[all:vars]
# Configurações globais para evitar checagem de chave em lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
python_interpreter=/usr/bin/python3
